config/routes.rb
Rails.application.routes.draw do
  root to: 'quizzes#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'

  resources :users, except: [:index, :destroy]
  resources :quizzes, except: [:index, :destroy] do 
    resources :puzzles, only: [:create]
  end
end

app/models/puzzle.rb
class Puzzle < ActiveRecord::Base
  belongs_to :quiz

  def correct_answer?
    if question[0..1] == ANSWERS[answer].first || question[0..1] == ANSWERS[answer].last
      true
    end
  end

  ANSWERS = {'1' => ['C0'], 
             '2' => ['CS', 'Db'], 
             '3' => ['D0'], 
             '4' => ['DS', 'Eb'], 
             '5' => ['E0'], 
             '6' => ['F0'], 
             '7' => ['FS','Gb'], 
             '8' => ['G0'], 
             '9' => ['GS', 'Ab'], 
             '10' => ['A0'], 
             '11' => ['AS', 'Bb'], 
             '12' => ['B0']}
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  belongs_to :user
  has_many :puzzles

  CATEGORIES = ["Treble", "Base", "Both"]

  def calculate_score
    puzzles.length
  end

  def self.top_scores
    order(score: :desc).limit(5)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :quizzes, -> {order("created_at DESC")}
  has_secure_password validations: false
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "Must be logged in to do that."
      redirect_to root_path
    end
  end
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  before_action :require_user

  def create
    @quiz = Quiz.find(params[:quiz_id])
    @puzzle = @quiz.puzzles.build(puzzle_params)

    if @puzzle.correct_answer?
      @quiz.score = @quiz.calculate_score
      @quiz.save
      redirect_to @quiz
    else
      @quiz.save
      flash[:danger] = "Game Over. Score: #{@quiz.score}"
      redirect_to user_path(current_user)
    end
  end

  private

  def puzzle_params
    params.require(:puzzle).permit(:question, :answer)
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :require_user, only: [:show, :create]
  before_action :set_quiz, only: [:show]

  def index
    @quiz = Quiz.new
    @quizzes = Quiz.all
  end

  def show
    @puzzle = Puzzle.new
  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.user = current_user
    @quiz.save
    render :show
  end

  private 

  def quiz_params
    params.require(:quiz).permit(:category, :score)
  end 

  def set_quiz
    @quiz = Quiz.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.where(username: params[:username]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id 
      flash[:notice] = "Welcome, you've logged in!"
      redirect_to root_path
    else
      flash[:danger] = "There is something wrong with your username or password"
      redirect_to login_path
    end 
  end 

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out!"
    redirect_to root_path
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def show
    @quiz = Quiz.all 
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You are registered."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def random_question(quiz_type)
    question = random_note + random_clef(quiz_type) + random_octave 
  end

  def random_note
    a_notes = ['AS', 'A0', 'Ab']
    b_notes = ['B0', 'Bb']
    c_notes = ['CS', 'C0']
    d_notes = ['DS', 'D0', 'Db']
    e_notes = ['E0', 'Eb']
    f_notes = ['FS', 'F0']
    g_notes = ['GS', 'G0', 'Gb']

    all_notes = a_notes + b_notes + c_notes + d_notes + e_notes + f_notes + g_notes
    all_notes.sample
  end

  def random_clef(quiz_type)
    treble_clef = 'T'
    base_clef = 'B'
    clefs = []

    if quiz_type == "Treble"
      clefs = [treble_clef]
    elsif quiz_type == "Base"
      clefs = [base_clef]
    elsif quiz_type == "Both"
      clefs = [treble_clef,base_clef]
    end

    clefs.sample.to_s
  end

  def random_octave
    treble_octaves = [4,5]
    base_octaves = [2,3]
    first_octaves = [3,4]
    first_octaves.sample.to_s
    octave = '1'
  end

  def key_image_path(index)
    if (index == 2 || index == 4 || index == 7 || index == 9 || index == 11)
      "/images/piano/black.png"
    else
      "/images/piano/white.png"
    end
  end

  def note_image_path(question)
    path = nil
    if question[2] == 'T'
      path = "/images/piano/treble/#{question[3]}/#{question[0..1]}.png"
    elsif question[2] == 'B'
      path = "/images/piano/base/#{question[3]}/#{question[0..1]}.png"
    end
  end

  def note_sound_path(question)
    "public/audios/" + question + ".jpg"
  end

  def display_datetime(dt)
    dt = dt.in_time_zone('Eastern Time (US & Canada)')
    dt.strftime("%m/%d/%Y %l:%M%P %Z") 
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Quizzes</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      
        <% if logged_in? %>

          <!-- <li><%= link_to 'LINK 1' %></li>
          <li><%= link_to 'LINK 2' %></li> -->

          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to edit_user_path(current_user) do %>
              <i class='icon-pencil'></i>
              edit profile
              <% end %>
            </li>
            <li>
              <%= link_to user_path(current_user) do %>
                <i class='icon-user'></i>
                view profile
              <% end %>
            </li>
            <li>
              <%= link_to logout_path do %>
                <i class='icon-circle-arrow-left'></i>
                logout
              <% end %>
            </li>
          </ul>
        </li>
        <% else %>
        <li>
          <i class='icon-pencil'></i>
          <%= link_to 'Register', register_path %>
        </li>
        <li>
          <%= link_to 'Log in', login_path %>
        </li>
        <% end %> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Piano Quiz</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/quizzes/index.html.erb
<%= render 'shared/content_title', title: 'Pick a Quiz!' %>

<% Quiz::CATEGORIES.each do |category| %>
  <%= form_for @quiz do |f| %>
    <div class='control-group'>
      <%= f.hidden_field :category, :value => "#{category}" %>
      <%= f.hidden_field :score, :value => 0 %>
    </div>
    <%= f.submit "#{category}", class: "btn btn-default btn-lg btn-block" %>
  <% end %>
  </br>
<% end %> 
</br>
</br>
</br>  
<p>
  <h5>Top 5 Scores</h5>
  <% @quizzes.top_scores.each  do |quiz| %>
    <div class='btn btn-default btn-lg btn-block'>
      <p>
          User: <%= link_to quiz.user.username, user_path(quiz.user) %>
      </br>
          Quiz Category: <%= quiz.category %>
      </br>
          Score: <%= quiz.score %>
      </br>
          Date: <%= display_datetime(quiz.created_at) %>
    </div>
  <% end %>
</p>

app/views/quizzes/show.html.erb
<h2> Score: <%= @quiz.score %> </h2>
<% question = random_question(@quiz.category) %>

<%= image_tag(note_image_path(question), size:"304x228") %>

<% piano_style = [ 'left: 0px; z-index: 0;',
                   'left: 42px; z-index: 1;',
                   'left: 62px; z-index: 0;',
                   'left: 104px; z-index: 1;',
                   'left: 124px; z-index: 0;',
                   'left: 186px; z-index: 0;',
                   'left: 228px; z-index: 1;',
                   'left: 248px; z-index: 0;',
                   'left: 290px; z-index: 1;',
                   'left: 310px; z-index: 0;',
                   'left: 352px; z-index: 1;',
                   'left: 372px; z-index: 0;'] %>

</br>
</br>

<% 12.times do |index| %>
  <%= form_for [@quiz, Puzzle.new], :html => { :style => 'position: absolute; top: 420px;' + piano_style[index].to_s} do |f| %>
      <%= f.hidden_field :answer, :value => index+1 %>
      <%= f.hidden_field :question, :value => question %>
      <%= f.submit "Button Number #{index+1}", :type => :image, :src => key_image_path(index+1) %>
  <% end %>
<% end %>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  <hr/>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'>
    <div class='alert alert-errors span8'>
      <h5> There were some errors: </h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class='well'>
  <h4> Name: <%= @user.username %> </h4>
  <%= form_for @user , :html => {:class => "form-horizontal center"} do |f| %>
    <%= render 'shared/errors', obj: @user %>
      <div class='form-group'>
        <%= f.label :username,  class: "col-sm-2 control-label" %>
        <div class="col-lg-4">
        <%= f.text_field :username, class: "form-control" %>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label :password,  class: "col-sm-2 control-label" %>
      <div class="col-lg-4">
        <%= f.text_field :password, class: "form-control" %>
        </div>
      </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit (@user.new_record? ? "Register" : "Update Profile"), class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<% render 'shared/content_title', title: "Edit Profile" %>
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register' %>
<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>

<div class='well'>
  <dl class='dl-horizontal'>
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
    <dt>Quizzes taken:</dt>
    <dd><%= @user.quizzes.count %></dd>    
  </dt>
</div>

<h5><%= @user.username %>'s Top Scores</h5>
  <% @user.quizzes.each do |user_quiz| %>
    <div class=' btn btn-default btn-lg btn-block'>
      <p>
          Quiz Category: <%= user_quiz.category %>
      </br>
          Score: <%= user_quiz.score %>
      </br>
          Date: <%= display_datetime(user_quiz.created_at) %>
    </div>
  <% end %>

  